# Generated by Django 4.2.11 on 2025-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=100)),
                ('wikipedia_url', models.CharField(max_length=100)),
                ('launches', models.JSONField(default=list)),
                ('status', models.CharField(max_length=20)),
                ('member_id', models.CharField(max_length=50)),
            ],
        ),
    ]
