# Generated by Django 4.2.11 on 2025-10-05 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacex_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capsule', models.CharField(max_length=255)),
                ('mass_returned_kg', models.FloatField()),
                ('mass_returned_lbs', models.FloatField()),
                ('flight_time_sec', models.IntegerField()),
                ('manifest', models.URLField()),
                ('water_landing', models.BooleanField()),
                ('land_landing', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='agency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='wikipedia_url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('reused', models.BooleanField(default=False)),
                ('launch', models.CharField(max_length=255)),
                ('customers', models.JSONField(default=list)),
                ('nationalities', models.JSONField(default=list)),
                ('manufacturers', models.JSONField(default=list)),
                ('norad_ids', models.JSONField(default=list)),
                ('mass_kg', models.FloatField()),
                ('mass_lbs', models.FloatField()),
                ('orbit', models.CharField(max_length=50)),
                ('reference_system', models.CharField(max_length=50)),
                ('regime', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('semi_major_axis_km', models.FloatField()),
                ('eccentricity', models.FloatField()),
                ('periapsis_km', models.FloatField()),
                ('apoapsis_km', models.FloatField()),
                ('inclination_deg', models.FloatField()),
                ('period_min', models.FloatField()),
                ('lifespan_years', models.IntegerField()),
                ('epoch', models.DateTimeField()),
                ('mean_motion', models.FloatField()),
                ('raan', models.FloatField()),
                ('arg_of_pericenter', models.FloatField()),
                ('mean_anomaly', models.FloatField()),
                ('dragon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex_app.dragon')),
            ],
        ),
    ]
