# Generated by Django 4.2.11 on 2025-10-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex_app', '0002_dragon_alter_crewmember_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='launches',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='member_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='capsule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='flight_time_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='land_landing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='manifest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='mass_returned_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='mass_returned_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='water_landing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='apoapsis_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='arg_of_pericenter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='customers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='eccentricity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='epoch',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='inclination_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='launch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='lifespan_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='manufacturers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='mass_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='mass_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='mean_anomaly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='mean_motion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='nationalities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='norad_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='payload_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='periapsis_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='period_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='raan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='reference_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='regime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='reused',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='semi_major_axis_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
