# Generated by Django 4.2.11 on 2025-10-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex_app', '0003_alter_crewmember_agency_alter_crewmember_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='orbit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
