# Generated by Django 4.2.11 on 2025-10-05 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacex_app', '0004_alter_payload_orbit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlickrLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.JSONField(blank=True, default=list, null=True)),
                ('original', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.CharField(blank=True, max_length=255, null=True)),
                ('flight', models.IntegerField(blank=True, null=True)),
                ('gridfins', models.BooleanField(blank=True, null=True)),
                ('legs', models.BooleanField(blank=True, null=True)),
                ('reused', models.BooleanField(blank=True, null=True)),
                ('landing_attempt', models.BooleanField(blank=True, null=True)),
                ('landing_success', models.BooleanField(blank=True, null=True)),
                ('landing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('landpad', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.URLField(blank=True, null=True)),
                ('large', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedditLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.URLField(blank=True, null=True)),
                ('launch', models.URLField(blank=True, null=True)),
                ('media', models.URLField(blank=True, null=True)),
                ('recovery', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presskit', models.URLField(blank=True, null=True)),
                ('webcast', models.URLField(blank=True, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=50, null=True)),
                ('article', models.URLField(blank=True, null=True)),
                ('wikipedia', models.URLField(blank=True, null=True)),
                ('flickr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex_app.flickrlinks')),
                ('patch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex_app.patchlinks')),
                ('reddit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex_app.redditlinks')),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_id', models.CharField(max_length=255)),
                ('fairings', models.JSONField(blank=True, null=True)),
                ('static_fire_date_utc', models.DateTimeField(blank=True, null=True)),
                ('static_fire_date_unix', models.IntegerField(blank=True, null=True)),
                ('tdb', models.BooleanField(blank=True, null=True)),
                ('net', models.BooleanField(blank=True, null=True)),
                ('window', models.IntegerField(blank=True, null=True)),
                ('rocket', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('failures', models.JSONField(blank=True, default=list, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ships', models.JSONField(blank=True, default=list, null=True)),
                ('capsules', models.JSONField(blank=True, default=list, null=True)),
                ('launchpad', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_update', models.BooleanField(blank=True, null=True)),
                ('flight_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_utc', models.DateTimeField(blank=True, null=True)),
                ('date_unix', models.IntegerField(blank=True, null=True)),
                ('date_local', models.DateTimeField(blank=True, null=True)),
                ('date_precision', models.CharField(blank=True, max_length=50, null=True)),
                ('upcoming', models.BooleanField(blank=True, null=True)),
                ('cores', models.ManyToManyField(blank=True, to='spacex_app.launchcore')),
                ('crew', models.ManyToManyField(blank=True, to='spacex_app.crewmember')),
                ('links', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex_app.launchlinks')),
                ('payloads', models.ManyToManyField(blank=True, related_name='launches', to='spacex_app.payload')),
            ],
        ),
    ]
