# Generated by Django 4.2.11 on 2025-10-05 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacex_app', '0005_flickrlinks_launchcore_patchlinks_redditlinks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchlinks',
            name='flickr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex_app.flickrlinks'),
        ),
        migrations.AlterField(
            model_name='launchlinks',
            name='patch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex_app.patchlinks'),
        ),
        migrations.AlterField(
            model_name='launchlinks',
            name='reddit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex_app.redditlinks'),
        ),
    ]
