# Generated by Django 4.2.11 on 2025-10-07 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacex_app', '0006_alter_launchlinks_flickr_alter_launchlinks_patch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='dragon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacex_app.dragon'),
        ),
    ]
